// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import "github.com/conduitio/conduit-commons/config"

func (Config) Parameters() config.Parameters {
	return map[string]config.Parameter{
		"connection": {
			Default:     "",
			Description: "connection string connection to SQL Server database.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"table": {
			Default:     "",
			Description: "table is a name of the table that the connector should write to or read from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
