// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package source

import "github.com/conduitio/conduit-commons/config"

func (Config) Parameters() config.Parameters {
	return map[string]config.Parameter{
		"batchSize": {
			Default:     "1000",
			Description: "batchSize is a size of rows batch.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{Value: 1},
				config.ValidationLessThan{Value: 100000},
			},
		},
		"columns": {
			Default:     "",
			Description: "columns  list of column names that should be included in each Record's payload.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"connection": {
			Default:     "",
			Description: "connection string connection to SQL Server database.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"orderingColumn": {
			Default:     "",
			Description: "orderingColumn is a name of a column that the connector will use for ordering rows.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"primaryKey": {
			Default:     "",
			Description: "primaryKey - Column name that records should use for their `primaryKey` fields.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"snapshot": {
			Default:     "true",
			Description: "snapshot whether the plugin will take a snapshot of the entire table before starting cdc.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"table": {
			Default:     "",
			Description: "table is a name of the table that the connector should write to or read from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
